name: buildx
on: [push, pull_request]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
    - name: Build platforms
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --file Dockerfile \
          . \
          -t iqtlabs/uhd_sample_recorder
